apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "50m"
          memory: "200Mi"
        limits:
          cpu: "100m"
          memory: "400Mi"
