apiVersion: v1
kind: Pod
metadata:
  name: environments-demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: DevOps
        - name: trainer
          value: SivaKumar
