apiVersion: v1
kind: Pod
metadata:
  name: config-map-demo

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        containerport: 80
      envFrom:
        - configmapRef:
            name: pod-config
